version: '3'
services:
  mysql:
    image: 'mysql:9.0.1'
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
      - logs:/var/log/mysql
    ports:
      - '3306:3306'
    networks:
      - network   # сеть будет называться mysql_network
    logging:
      driver: json-file
      options:
        max-size: "10m"   # Максимальный размер файла лога
        max-file: "14"    # Максимальное количество файлов логов
        compress: "true"   # Включение сжатия файлов логов

networks:
  network:    # сеть будет называться mysql_network
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.248.0/24

volumes:
  db-data:
  logs:
